FROM node:alpine

RUN mkdir -p /usr/src/
WORKDIR /usr/src/

COPY . /usr/src/

ENV AZURE_SEARCH_ENDPOINT=${AZURE_SEARCH_ENDPOINT}
ENV AZURE_SEARCH_KEY=${AZURE_SEARCH_KEY}
ENV AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}
ENV AZURE_SEARCH_VECTOR_FIELD=${AZURE_SEARCH_VECTOR_FIELD}
ENV AZURE_SEARCH_CONTENT_FIELD=${AZURE_SEARCH_CONTENT_FIELD}
ENV AZURE_SEARCH_SEMANTIC_CONFIGURATION_NAME=${AZURE_SEARCH_SEMANTIC_CONFIGURATION_NAME}
ENV AZURE_OPENAI_API_ENDPOINT=${AZURE_OPENAI_API_ENDPOINT}
ENV AZURE_RESOURCE_NAME=${AZURE_RESOURCE_NAME}
ENV AZURE_DEPLOYMENT_NAME=${AZURE_DEPLOYMENT_NAME}
ENV AZURE_EMBEDDING_DEPLOYMENT_NAME=${AZURE_EMBEDDING_DEPLOYMENT_NAME}
ENV AZURE_API_KEY=${AZURE_API_KEY}

RUN npm install

RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]